from .config import METAFILE as METAFILE, get_current_context_name as get_current_context_name, get_meta_dir as get_meta_dir, write_context_name_to_docker_config as write_context_name_to_docker_config
from .context import Context as Context
from _typeshed import Incomplete
from docker import errors as errors

class ContextAPI:
    DEFAULT_CONTEXT: Incomplete
    @classmethod
    def create_context(cls, name, orchestrator=None, host=None, tls_cfg=None, default_namespace=None, skip_tls_verify: bool = False): ...
    @classmethod
    def get_context(cls, name=None): ...
    @classmethod
    def contexts(cls): ...
    @classmethod
    def get_current_context(cls): ...
    @classmethod
    def set_current_context(cls, name: str = 'default') -> None: ...
    @classmethod
    def remove_context(cls, name) -> None: ...
    @classmethod
    def inspect_context(cls, name: str = 'default'): ...
