from docker import utils as utils
from docker.constants import DEFAULT_UNIX_SOCKET as DEFAULT_UNIX_SOCKET, IS_WINDOWS_PLATFORM as IS_WINDOWS_PLATFORM
from docker.utils.config import find_config_file as find_config_file

METAFILE: str

def get_current_context_name(): ...
def write_context_name_to_docker_config(name=None): ...
def get_context_id(name): ...
def get_context_dir(): ...
def get_meta_dir(name=None): ...
def get_meta_file(name): ...
def get_tls_dir(name=None, endpoint: str = ''): ...
def get_context_host(path=None, tls: bool = False): ...
