# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  deploy:
    sources:
      - main.py
      - cheminfra/*.py
      - cheminfra/**/*.py
    cmds:
      - rsync -avHSP --exclude '.task' --exclude '.venv' --exclude '.git' --exclude '__pycache__' --exclude '.mypy_cache' ./ ubuntu@shulgin.scurry.io:/home/ubuntu/cheminfra/
  health:
    deps:
      - deploy
    cmds:
      - ssh ubuntu@shulgin.scurry.io "cd /home/ubuntu/cheminfra && uv sync && sudo /home/ubuntu/.local/bin/uv run python main.py health"
  test:
    cmds:
      - uv run pytest
