# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  rollout:
    cmds:
      - task: "ui:build"
      - task: "deploy:run"
  health:
    deps:
      - deploy
    cmds:
      - ssh ubuntu@shulgin.scurry.io "cd /home/ubuntu/cheminfra && uv sync && sudo /home/ubuntu/.local/bin/uv run python main.py health"
  test:
    cmds:
      - uv run pytest

includes:
  deploy:
    dir: deploy
    taskfile: deploy/Taskfile.yaml
  ui:
    dir: ui
    taskfile: ui/Taskfile.yaml
