from fire.console import console_attr as console_attr, console_pager as console_pager, encoding as encoding, files as files

def IsInteractive(output: bool = False, error: bool = False, heuristic: bool = False): ...
def More(contents, out, prompt=None, check_pager: bool = True) -> None: ...
