def Encode(string, encoding=None): ...
def Decode(data, encoding=None): ...
def GetEncodedValue(env, name, default=None): ...
def SetEncodedValue(env, name, value, encoding=None) -> None: ...
def EncodeEnv(env, encoding=None): ...
