package health

func ExpectedContainerNames() []string {
	return []string{
		"/deploy-celery_workers-1",
		"/deploy-app-1",
		"/retro_star",
		"/mcts",
		"/expand_one",
		"/solubility",
		"/site_selectivity",
		"/scscore",
		"/retro_template_relevance",
		"/retro_retrosim",
		"/retro_graph2smiles",
		"/retro_augmented_transformer",
		"/reaction_class",
		"/qm_descriptors",
		"/pmi_calculator",
		"/pathway_ranker",
		"/impurity_predictor",
		"/general_selectivity",
		"/forward_wldn5",
		"/forward_graph2smiles",
		"/forward_augmented_transformer",
		"/fast_filter",
		"/evaluate_reactions",
		"/descriptors",
		"/count_analogs",
		"/context_recommender",
		"/cluster",
		"/atom_map_wln",
		"/atom_map_rxnmapper",
		"/atom_map_indigo",
		"/deploy-mongo-1",
		"/deploy-web-1",
		"/deploy-rabbitmq-1",
		"/deploy-redis-1",
	}
}
