from fire import inspectutils as inspectutils

def Script(name, component, default_options=None, shell: str = 'bash'): ...
def MemberVisible(component, name, member, class_attrs=None, verbose: bool = False): ...
def VisibleMembers(component, class_attrs=None, verbose: bool = False): ...
def Completions(component, verbose: bool = False): ...
