from fire import completion as completion, testutils as testutils

class TabCompletionTest(testutils.BaseTestCase):
    def testCompletionBashScript(self) -> None: ...
    def testCompletionFishScript(self) -> None: ...
    def testFnCompletions(self): ...
    def testListCompletions(self) -> None: ...
    def testDictCompletions(self) -> None: ...
    def testDictCompletionsVerbose(self) -> None: ...
    def testDeepDictCompletions(self) -> None: ...
    def testDeepDictScript(self) -> None: ...
    def testFnScript(self) -> None: ...
    def testClassScript(self) -> None: ...
    def testDeepDictFishScript(self) -> None: ...
    def testFnFishScript(self) -> None: ...
    def testClassFishScript(self) -> None: ...
    def testNonStringDictCompletions(self) -> None: ...
    def testGeneratorCompletions(self) -> None: ...
    def testClassCompletions(self) -> None: ...
    def testObjectCompletions(self) -> None: ...
    def testMethodCompletions(self) -> None: ...
