from fire import core as core, testutils as testutils, trace as trace

class CoreTest(testutils.BaseTestCase):
    def testOneLineResult(self) -> None: ...
    def testOneLineResultCircularRef(self) -> None: ...
    def testInteractiveMode(self, mock_embed) -> None: ...
    def testInteractiveModeFullArgument(self, mock_embed) -> None: ...
    def testInteractiveModeVariables(self, mock_embed) -> None: ...
    def testInteractiveModeVariablesWithName(self, mock_embed) -> None: ...
    def testHelpWithClass(self) -> None: ...
    def testHelpWithMember(self) -> None: ...
    def testHelpOnErrorInConstructor(self) -> None: ...
    def testHelpWithNamespaceCollision(self) -> None: ...
    def testInvalidParameterRaisesFireExit(self) -> None: ...
    def testErrorRaising(self) -> None: ...
    def testFireError(self) -> None: ...
    def testFireErrorMultipleValues(self) -> None: ...
    def testPrintEmptyDict(self) -> None: ...
    def testPrintOrderedDict(self) -> None: ...
    def testPrintNamedTupleField(self) -> None: ...
    def testPrintNamedTupleFieldNameEqualsValue(self) -> None: ...
    def testPrintNamedTupleIndex(self) -> None: ...
    def testPrintSet(self) -> None: ...
    def testPrintFrozenSet(self) -> None: ...
    def testPrintNamedTupleNegativeIndex(self) -> None: ...
    def testCallable(self) -> None: ...
    def testCallableWithPositionalArgs(self) -> None: ...
    def testStaticMethod(self) -> None: ...
    def testClassMethod(self) -> None: ...
    def testCustomSerialize(self): ...
    def testLruCacheDecoratorBoundArg(self) -> None: ...
    def testLruCacheDecorator(self) -> None: ...
