from _typeshed import Incomplete
from fire import formatting as formatting

TWO_DOUBLE_QUOTES: str
STRING_DESC_PREFIX: str

def NeedsCustomDescription(component): ...
def GetStringTypeSummary(obj, available_space, line_length): ...
def GetStringTypeDescription(obj, available_space, line_length): ...

CUSTOM_DESC_SUM_FN_DICT: Incomplete

def GetSummary(obj, available_space, line_length): ...
def GetDescription(obj, available_space, line_length): ...
