from fire import custom_descriptions as custom_descriptions, testutils as testutils

LINE_LENGTH: int

class CustomDescriptionTest(testutils.BaseTestCase):
    def test_string_type_summary_enough_space(self) -> None: ...
    def test_string_type_summary_not_enough_space_truncated(self) -> None: ...
    def test_string_type_summary_not_enough_space_new_line(self) -> None: ...
    def test_string_type_summary_not_enough_space_long_truncated(self) -> None: ...
    def test_string_type_description_enough_space(self) -> None: ...
    def test_string_type_description_not_enough_space_truncated(self) -> None: ...
    def test_string_type_description_not_enough_space_new_line(self) -> None: ...
