from fire import core as core, decorators as decorators, testutils as testutils

class NoDefaults:
    def double(self, count): ...
    def triple(self, count): ...
    def quadruple(self, count): ...

def double(count): ...

class WithDefaults:
    def example1(self, arg1: int = 10): ...
    def example2(self, arg1: int = 10): ...

class MixedArguments:
    def example3(self, arg1, arg2): ...

class PartialParseFn:
    def example4(self, arg1, arg2): ...
    def example5(self, arg1, arg2): ...

class WithKwargs:
    def example6(self, **kwargs): ...

class WithVarArgs:
    def example7(self, arg1, arg2=None, *varargs, **kwargs): ...

class FireDecoratorsTest(testutils.BaseTestCase):
    def testSetParseFnsNamedArgs(self) -> None: ...
    def testSetParseFnsPositionalArgs(self) -> None: ...
    def testSetParseFnsFnWithPositionalArgs(self) -> None: ...
    def testSetParseFnsDefaultsFromPython(self) -> None: ...
    def testSetParseFnsDefaultsFromFire(self) -> None: ...
    def testSetParseFnsNamedDefaultsFromPython(self) -> None: ...
    def testSetParseFnsNamedDefaultsFromFire(self) -> None: ...
    def testSetParseFnsPositionalAndNamed(self) -> None: ...
    def testSetParseFnsOnlySomeTypes(self) -> None: ...
    def testSetParseFnsForKeywordArgs(self) -> None: ...
    def testSetParseFn(self) -> None: ...
