from typing import Any

FIRE_METADATA: str
FIRE_PARSE_FNS: str
ACCEPTS_POSITIONAL_ARGS: str

def SetParseFn(fn, *arguments): ...
def SetParseFns(*positional, **named): ...
def GetMetadata(fn) -> dict[str, Any]: ...
def GetParseFns(fn) -> dict[str, Any]: ...
