from fire import testutils as testutils

class FireImportTest(testutils.BaseTestCase):
    def testFire(self) -> None: ...
    def testFireMethods(self) -> None: ...
    def testNoPrivateMethods(self) -> None: ...
