from fire import formatting_windows as formatting_windows

ELLIPSIS: str

def Indent(text, spaces: int = 2): ...
def Bold(text): ...
def Underline(text): ...
def BoldUnderline(text): ...
def WrappedJoin(items, separator: str = ' | ', width: int = 80): ...
def Error(text): ...
def EllipsisTruncate(text, available_space, line_length): ...
def EllipsisMiddleTruncate(text, available_space, line_length): ...
def DoubleQuote(text): ...
