from _typeshed import Incomplete
from fire import docstrings as docstrings

class FullArgSpec:
    args: Incomplete
    varargs: Incomplete
    varkw: Incomplete
    defaults: Incomplete
    kwonlyargs: Incomplete
    kwonlydefaults: Incomplete
    annotations: Incomplete
    def __init__(self, args=None, varargs=None, varkw=None, defaults=None, kwonlyargs=None, kwonlydefaults=None, annotations=None) -> None: ...

def Py3GetFullArgSpec(fn): ...
def GetFullArgSpec(fn): ...
def GetFileAndLine(component): ...
def Info(component): ...
def IsNamedTuple(component): ...
def GetClassAttrsDict(component): ...
def IsCoroutineFunction(fn): ...
