from _typeshed import Incomplete
from fire import __main__ as __main__, testutils as testutils

class MainModuleTest(testutils.BaseTestCase):
    def testNameSetting(self) -> None: ...
    def testArgPassing(self) -> None: ...

class MainModuleFileTest(testutils.BaseTestCase):
    file: Incomplete
    file2: Incomplete
    def setUp(self) -> None: ...
    def testFileNameFire(self) -> None: ...
    def testFileNameFailure(self) -> None: ...
    def testFileNameModuleDuplication(self) -> None: ...
    def testFileNameModuleFileFailure(self) -> None: ...
