from fire import testutils as testutils

class TestTestUtils(testutils.BaseTestCase):
    def testNoCheckOnException(self) -> None: ...
    def testCheckStdoutOrStderrNone(self) -> None: ...
    def testCorrectOrderingOfAssertRaises(self) -> None: ...
