from _typeshed import Incomplete
from fire import inspectutils as inspectutils

VALUE_TYPES: Incomplete

def IsGroup(component): ...
def IsCommand(component): ...
def IsValue(component): ...
def IsSimpleGroup(component): ...
def HasCustomStr(component): ...
