from ..api import APIClient as APIClient
from .resource import Collection as Collection, Model as Model

class Volume(Model):
    id_attribute: str
    @property
    def name(self): ...
    def remove(self, force: bool = False): ...

class VolumeCollection(Collection):
    model = Volume
    def create(self, name=None, **kwargs): ...
    def get(self, volume_id): ...
    def list(self, **kwargs): ...
    def prune(self, filters=None): ...
