import requests.adapters

class BaseHTTPAdapter(requests.adapters.HTTPAdapter):
    def close(self) -> None: ...
    def get_connection_with_tls_context(self, request, verify, proxies=None, cert=None): ...
