from .. import auth as auth, types as types, utils as utils

class DaemonApiMixin:
    def df(self): ...
    def events(self, since=None, until=None, filters=None, decode=None): ...
    def info(self): ...
    def login(self, username, password=None, email=None, registry=None, reauth: bool = False, dockercfg_path=None): ...
    def ping(self): ...
    def version(self, api_version: bool = True): ...
