from .. import utils as utils
from ..errors import InvalidVersion as InvalidVersion
from ..utils import check_resource as check_resource, minimum_version as minimum_version, version_lt as version_lt

class NetworkApiMixin:
    def networks(self, names=None, ids=None, filters=None): ...
    def create_network(self, name, driver=None, options=None, ipam=None, check_duplicate=None, internal: bool = False, labels=None, enable_ipv6: bool = False, attachable=None, scope=None, ingress=None): ...
    def prune_networks(self, filters=None): ...
    def remove_network(self, net_id) -> None: ...
    def inspect_network(self, net_id, verbose=None, scope=None): ...
    def connect_container_to_network(self, container, net_id, ipv4_address=None, ipv6_address=None, aliases=None, links=None, link_local_ips=None, driver_opt=None, mac_address=None) -> None: ...
    def disconnect_container_from_network(self, container, net_id, force: bool = False) -> None: ...
