from .. import errors as errors, utils as utils

class SecretApiMixin:
    def create_secret(self, name, data, labels=None, driver=None): ...
    def inspect_secret(self, id): ...
    def remove_secret(self, id): ...
    def secrets(self, filters=None): ...
