from .. import errors as errors, utils as utils

class VolumeApiMixin:
    def volumes(self, filters=None): ...
    def create_volume(self, name=None, driver=None, driver_opts=None, labels=None): ...
    def inspect_volume(self, name): ...
    def prune_volumes(self, filters=None): ...
    def remove_volume(self, name, force: bool = False) -> None: ...
